#accessLog:
#  addInternals: true
#  format: json
#  fields:
#    defaultMode: keep
#    names:
#      ClientUsername: drop
#    headers:
#      defaultMode: keep
#      names:
#        User-Agent: redact
#        Authorization: drop
#        Content-Type: keep
log: 
  level: "ERROR" 
api:
  insecure: true
  dashboard: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    endpoint: "tcp://dockerproxy:2375"
    network: "services"
  file:
    filename: traefik.yaml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: andrei.moculescu@proton.me
      storage: acme.json
        #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
          
## DYNAMIC CONFIGURATION
http:
  routers:
    pve:
      entryPoints:
        - https
      rule: "Host(`pve.moculescu.de`)"
      middlewares:
        - default-headers
        # - https-redirectscheme
      tls: {}
      service: pve
    reactive-resume:
      entryPoints:
        - https
      rule: "Host(`resume.moculescu.de`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: reactive-resume
    pihole:
      entryPoints:
        - https
      rule: "Host(`pihole.moculescu.de`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - pihole-redirect
        - pihole-addprefix
      tls: {}
      service: pihole
    pihole-alt:
      entryPoints:
        - https
      rule: "Host(`pihole2.moculescu.de`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - pihole-redirect
        - pihole-addprefix
      tls: {}
      service: pihole-alt
      
  services:
    pve:
      loadbalancer:
        servers:
          - url: "https://192.168.178.4:8006"
        passHostHeader: true
        serversTransport: "pve"
    reactive-resume:
      loadbalancer:
        servers:
          - url: "http://192.168.178.50:3000"
        passHostHeader: true
        serversTransport: "pve"
    pihole:
      loadbalancer:
        servers:
          - url: "http://192.168.178.2:80"
        passHostHeader: true
    pihole-alt:
      loadbalancer:
        servers:
          - url: "http://192.168.178.3:80"
        passHostHeader: true
        
  middlewares:
    pihole-addprefix:
      addPrefix:
        prefix: "/admin"
    pihole-redirect:
      redirectRegex:
        regex: "/admin/$"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
          
  serversTransports:
    pve:
      insecureSkipVerify:
        true
