#accessLog:
  #addInternals: true
  #format: json
  #fields:
  #defaultMode: keep
  #names:
  #ClientUsername: drop
  #headers:
  # defaultMode: keep
  # names:
  # User-Agent: redact
  #Authorization: drop
  #Content-Type: keep
log: 
  level: "ERROR" 
api:
  insecure: true
  dashboard: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    endpoint: "tcp://dockerproxy:2375"
    network: "services"

certificatesResolvers:
  cloudflare:
    acme:
      email: andrei.moculescu@proton.me
      storage: acme.json
        #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
