---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Internet:
    - PiHole:
        icon: pi-hole
        href: http://raspilin/admin
        description: PiHole admin panel

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- Entertainment:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
