---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - icon: github-light
          href: https://github.com/
    - gitlab:
        - icon: gitlab
          href: https://gitlab.com/

- Social:
    - Reddit:
        - icon: reddit
          href: https://old.reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube
          href: https://youtube.com/
    - Prime Video:
        - icon: prime-video-light
          href: https://www.amazon.de/gp/video/storefront
    - netflix:
        - icon: netflix
          href: https://www.netflix.com
    - twitch:
        - icon: twitch
          href: https://www.twitch.com
    - crunchyroll:
        - abbr: CR
          href: https://www.crunchyroll.com
