---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - PiHole:
        icon: pi-hole
        href: http://raspilin/admin
        description: PiHole admin panel
    - Traefic Dashboard:
        icon: traefik
        href: http://traefik.moculescu.de/dashboard

- Apps:
    - Reactive Resume:
        href: http://andreis-macbook-pro:3000
        icon: reactive-resume
        description: Resume builder

- Monitoring:
    - Grafana:
        icon: grafana
        href: http://grafana.moculescu.de/
        description: Grafana

    - Kuma:
        icon: uptime-kuma
        href: http://kuma.moculescu.de
        description: Uptime monitoring
